name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main  # Adjust this if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy  # This links to the 'deploy' environment you created

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Wrangler
        run: bunx wrangler@latest --version

      - name: Authenticate with Cloudflare
        run: echo "Authenticated with Cloudflare!"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy to Cloudflare Workers
        run: bun run deploy:worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

