name: Deploy to Cloudflare

on:
  push:
    branches:
      - main        # Production deployment
      - staging     # Staging deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'
          
      - name: Install dependencies using Bun
        run: bun install
        
      - name: Build the app using Bun
        run: bun run build
        
      - name: Deploy to Production using Wrangler
        if: github.ref == 'refs/heads/main'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: bun run deploy:worker -- --env=""
          
      - name: Deploy to Staging using Wrangler
        if: github.ref == 'refs/heads/staging'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: bun run deploy:worker -- --env staging
          
      - name: Comment on PR (if applicable)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const environment = github.ref === 'refs/heads/main' ? 'Production' : 'Staging';
            const url = github.ref === 'refs/heads/main' 
              ? 'https://lineups.nicolasvlavianos.workers.dev'
              : 'https://lineups-staging.nicolasvlavianos.workers.dev';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Successfully deployed to **${environment}**!\n\n📱 Preview: ${url}`
            });